[build]
  publish = "public"

[[edge_functions]]
  function = "relay"
  path = "/nf-0a3daaa6"

[[edge_functions]]
  function = "relay"
  path = "/nf-0a3daaa6/*"

[[edge_functions]]
  function = "relay"
  path = "/"
