[build]
  publish = "public"

[[edge_functions]]
  function = "relay"
  path = "/nf-d94e3af0"

[[edge_functions]]
  function = "relay"
  path = "/nf-d94e3af0/*"

[[edge_functions]]
  function = "relay"
  path = "/"
